### ISSUE TITLE
Białe znaki

### ISSUE THREAD

**Issue by smaciek513** [Arapak/sio-tool#6]
Pomimo ze wyjscie jest prawidlowe (takie same jak w sample oucie), wyswietlany jest komunikat "Failed" (prawdopodobnie przez wypisywanie endl na koniec). Czy da sie cos z tym zrobic?

![image](https://github.com/Arapak/sio-tool/assets/149587426/9cd31aa4-1340-43dd-b065-999bca01aab8)

**Comment by Arapak** [comment]
Tak, faktycznie, jeśli wypisywało się pustą linię, źle porównywały się outputy. Zauważyłem również że źle pobierały się testy przykładowe (nie powinno być tej części z wyjaśnieniem przykładu). Oba te błędy zostały naprawione w nowej wersji (przypominam, żeby pobrać nową wersję wystarczy użyć komendy `st upgrade`)
